export const routePaths = {
  public: {
    root: "/",
    landing: "/landing",
    login: "/login",
    register: "/register",
    identityVerification: "/identity-verification",
    onboarding: "/onboarding",
    explore: "/explore",
    workDetail: "/work/:id",
  },
  demo: {
    root: "/demo",
    desktopStudent: "/demo/desktop/student",
    mobileStudent: "/demo/mobile/student",
    desktopModerator: "/demo/desktop/moderator",
    mobileModerator: "/demo/mobile/moderator",
    desktopAdmin: "/demo/desktop/admin",
    mobileAdmin: "/demo/mobile/admin",
  },
  student: {
    home: "/student/home",
    explore: "/student/explore",
    gallery: "/student/gallery",
    events: "/student/events",
    spotlight: "/student/spotlight",
    submit: "/student/submit",
    notifications: "/student/notifications",
    profile: "/student/profile",
    search: "/student/search",
    searchResults: "/student/search-results",
    workDetail: "/student/work/:id",
    colleges: "/student/colleges",
    collegeShowcase: "/student/colleges/:collegeId",
    collegeWorkDetail: "/student/colleges/:collegeId/work/:id",
    creatorProfile: "/student/creator/:creatorId",
    exhibitionDetail: "/student/gallery/:exhibitionId",
    eventDetail: "/student/events/:eventId",
    eventEntry: "/student/events/:eventId/entry",
    editProfile: "/student/profile/edit",
    portfolio: "/student/profile/portfolio",
    submissions: "/student/submissions",
    submissionDetail: "/student/submissions/:submissionId",
    needsRevision: "/student/submissions/:submissionId/revision",
    reviseSubmission: "/student/submissions/:submissionId/revise",
    savedWorks: "/student/profile/saved",
    shareProfile: "/student/profile/share",
    submitBasicInformation: "/student/submit/basic-information",
    submitMedia: "/student/submit/media",
    submitClassification: "/student/submit/classification",
    submitOwnership: "/student/submit/ownership",
    submitReview: "/student/submit/review",
    submitConfirmation: "/student/submit/confirmation",
  },
  moderator: {
    dashboard: "/moderator/dashboard",
    pending: "/moderator/pending",
    review: "/moderator/review/:id",
    reports: "/moderator/reports",
    reportDetail: "/moderator/reports/:reportId",
    featured: "/moderator/featured",
    officialContent: "/moderator/official-content",
    history: "/moderator/history",
    events: "/moderator/events",
    newEvent: "/moderator/events/new",
  },
  admin: {
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    moderators: "/admin/moderators",
    colleges: "/admin/colleges",
    categories: "/admin/categories",
    events: "/admin/events",
    newEvent: "/admin/events/new",
    reports: "/admin/reports",
    featured: "/admin/featured",
    settings: "/admin/settings",
    auditLog: "/admin/audit-log",
  },
  preview: {
    prefix: "/preview",
    pattern: "/preview/*",
    example: "/preview/pup-campus-creatives/LandingDesktop",
  },
} as const;

export type RoutePaths = typeof routePaths;
