// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pup-campus-creatives/DesignSystem.tsx": () => import("../components/mockups/pup-campus-creatives/DesignSystem.tsx"),
  "./components/mockups/pup-campus-creatives/LandingDesktop.tsx": () => import("../components/mockups/pup-campus-creatives/LandingDesktop.tsx"),
  "./components/mockups/pup-campus-creatives/LandingMobile.tsx": () => import("../components/mockups/pup-campus-creatives/LandingMobile.tsx"),
  "./components/mockups/pup-campus-creatives/LoginPage.tsx": () => import("../components/mockups/pup-campus-creatives/LoginPage.tsx"),
  "./components/mockups/pup-campus-creatives/NotificationsPage.tsx": () => import("../components/mockups/pup-campus-creatives/NotificationsPage.tsx"),
  "./components/mockups/pup-campus-creatives/OnboardingPage.tsx": () => import("../components/mockups/pup-campus-creatives/OnboardingPage.tsx"),
  "./components/mockups/pup-campus-creatives/SignUpPage.tsx": () => import("../components/mockups/pup-campus-creatives/SignUpPage.tsx"),
  "./components/mockups/pup-campus-creatives/StudentHomeDesktop.tsx": () => import("../components/mockups/pup-campus-creatives/StudentHomeDesktop.tsx"),
  "./components/mockups/pup-campus-creatives/StudentHomeMobile.tsx": () => import("../components/mockups/pup-campus-creatives/StudentHomeMobile.tsx")
};
