export const OFFICIAL_CONTENT_SUBMISSIONS = [
  {
    id: 1,
    org: "PUP OSA",
    orgFull: "Office of Student Affairs",
    rep: "Ana Reyes",
    title: "PUP Likha 2026 - Winners Announcement",
    type: "Competition Result",
    date: "June 12",
    publishDate: "June 21, 2026",
    expirationDate: "August 2, 2026",
    status: "Pending",
    statusColor: "text-amber-700 bg-amber-50 border-amber-200",
    event: "PUP Likha 2026",
    verified: true,
    image: "/__mockup/images/event_1.jpg",
    excerpt: "Official winners card set for the university-wide creative showcase.",
    description:
      "A university-authored announcement package recognizing finalists and winners from PUP Likha 2026, prepared for publication across the Campus Creatives gallery and campus news surfaces.",
    audience: "All PUP students, faculty, alumni, and campus creative organizations",
    labelPreview: "Official PUP OSA Announcement",
  },
  {
    id: 2,
    org: "CCIS College",
    orgFull: "CCIS College Office",
    rep: "Prof. Santos",
    title: "CCIS Creatives Showcase 2026",
    type: "College Event",
    date: "June 10",
    publishDate: "June 18, 2026",
    expirationDate: "July 15, 2026",
    status: "Pending",
    statusColor: "text-amber-700 bg-amber-50 border-amber-200",
    event: "College Showcase",
    verified: true,
    image: "/__mockup/images/colleges/ccis-pup-main-building.jpg",
    excerpt: "A college feature announcing the next CCIS student creative showcase.",
    description:
      "An official CCIS College Office post inviting students to view and participate in the annual showcase of creative technology, multimedia, UI/UX, and digital art projects.",
    audience: "CCIS students, partner colleges, moderators, and invited campus guests",
    labelPreview: "Official CCIS College Office Post",
  },
  {
    id: 3,
    org: "VPSA Office",
    orgFull: "Office of the Vice President for Student Affairs",
    rep: "Dr. Cruz",
    title: "Foundation Week Poster Winners",
    type: "Official Announcement",
    date: "June 8",
    publishDate: "June 20, 2026",
    expirationDate: "July 30, 2026",
    status: "Approved",
    statusColor: "text-status-approved bg-status-approved/10 border-status-approved/20",
    event: "Foundation Week",
    verified: true,
    image: "/__mockup/images/event_2.jpg",
    excerpt: "Poster-making winners prepared for Foundation Week publication.",
    description:
      "A recognition post from the VPSA Office featuring the official winners and selected works from the Foundation Week poster-making activity.",
    audience: "University-wide audience and Foundation Week participants",
    labelPreview: "Official VPSA Recognition",
  },
  {
    id: 4,
    org: "CAL",
    orgFull: "College of Arts and Letters",
    rep: "Prof. Aquino",
    title: "Tinig ng PUP 2026 - Open Call Results",
    type: "Competition Result",
    date: "June 5",
    publishDate: "June 22, 2026",
    expirationDate: "August 15, 2026",
    status: "Needs Revision",
    statusColor: "text-status-needs-revision bg-status-needs-revision/10 border-status-needs-revision/20",
    event: "Tinig ng PUP 2026",
    verified: true,
    image: "/__mockup/images/event_3.jpg",
    excerpt: "Open-call results need clearer captioning before scheduling.",
    description:
      "A CAL official result post for Tinig ng PUP 2026. Moderator notes indicate the captions and representative authorization should be clarified before publication.",
    audience: "CAL students, spoken word participants, and campus arts community",
    labelPreview: "Official CAL Result Post",
  },
] as const;

export type OfficialContentSubmission = (typeof OFFICIAL_CONTENT_SUBMISSIONS)[number];
